import { getRandomProfilePic } from "./utils";

export const GITHUB_URL = "https://github.com/annnmol";

export const DUMMY_LISTING_DATA = Array.from({ length: 30 }, (_, index) => ({
  id: index + 1,
  name: `Day ${index + 1}`,
}));

export const DUMMY_USER = {
  id: 1,
  email: "anmol@hi2.in",
  name: "Anmol Tanwar",
  avatar: getRandomProfilePic("Anmol Tanwar"),
};

export const DUMMY_FLIGHT_DATA: IFlight[] = [
  {
    id: 1,
    gate: "A2",
    price: 5000,
    origin: "Delhi",
    airline: "IndiGo",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T11:00:00",
    destination: "Mumbai",
    flightNumber: "6E101",
    departureTime: "2024-03-15T08:00:00",
    seatsAvailable: 120,
  },
  {
    id: 2,
    gate: "B3",
    price: 6000,
    origin: "Delhi",
    airline: "Air India",
    aircraft: "Boeing 787",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T12:30:00",
    destination: "Bangalore",
    flightNumber: "AI202",
    departureTime: "2024-03-15T09:00:00",
    seatsAvailable: 100,
  },
  {
    id: 3,
    gate: "C1",
    price: 5500,
    origin: "Mumbai",
    airline: "SpiceJet",
    aircraft: "Boeing 737",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T13:30:00",
    destination: "Delhi",
    flightNumber: "SG303",
    departureTime: "2024-03-15T10:00:00",
    seatsAvailable: 90,
  },
  {
    id: 4,
    gate: "D2",
    price: 4500,
    origin: "Mumbai",
    airline: "Vistara",
    aircraft: "Airbus A320",
    duration: "2 hours 30 minutes",
    arrivalTime: "2024-03-15T13:30:00",
    destination: "Bangalore",
    flightNumber: "UK404",
    departureTime: "2024-03-15T11:00:00",
    seatsAvailable: 110,
  },
  {
    id: 5,
    gate: "A4",
    price: 6500,
    origin: "Bangalore",
    airline: "GoAir",
    aircraft: "Airbus A320",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T15:30:00",
    destination: "Delhi",
    flightNumber: "G805",
    departureTime: "2024-03-15T12:00:00",
    seatsAvailable: 80,
  },
  {
    id: 6,
    gate: "B2",
    price: 4000,
    origin: "Bangalore",
    airline: "AirAsia",
    aircraft: "Airbus A320",
    duration: "1 hour 30 minutes",
    arrivalTime: "2024-03-15T14:30:00",
    destination: "Mumbai",
    flightNumber: "I505",
    departureTime: "2024-03-15T13:00:00",
    seatsAvailable: 100,
  },
  {
    id: 7,
    gate: "C3",
    price: 5500,
    origin: "Delhi",
    airline: "IndiGo",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T12:30:00",
    destination: "Chennai",
    flightNumber: "6E107",
    departureTime: "2024-03-15T09:30:00",
    seatsAvailable: 120,
  },
  {
    id: 8,
    gate: "D4",
    price: 4800,
    origin: "Mumbai",
    airline: "Air India",
    aircraft: "Boeing 737",
    duration: "3 hours",
    arrivalTime: "2024-03-15T14:30:00",
    destination: "Chennai",
    flightNumber: "AI208",
    departureTime: "2024-03-15T11:30:00",
    seatsAvailable: 90,
  },
  {
    id: 9,
    gate: "A6",
    price: 6000,
    origin: "Bangalore",
    airline: "SpiceJet",
    aircraft: "Boeing 737",
    duration: "3 hours",
    arrivalTime: "2024-03-15T16:30:00",
    destination: "Kolkata",
    flightNumber: "SG309",
    departureTime: "2024-03-15T13:30:00",
    seatsAvailable: 100,
  },
  {
    id: 10,
    gate: "B7",
    price: 7000,
    origin: "Delhi",
    airline: "Vistara",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T17:00:00",
    destination: "Kolkata",
    flightNumber: "UK410",
    departureTime: "2024-03-15T14:00:00",
    seatsAvailable: 120,
  },
  {
    id: 11,
    gate: "C8",
    price: 6200,
    origin: "Mumbai",
    airline: "GoAir",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T18:00:00",
    destination: "Kolkata",
    flightNumber: "G811",
    departureTime: "2024-03-15T15:00:00",
    seatsAvailable: 80,
  },
  {
    id: 12,
    gate: "D1",
    price: 5400,
    origin: "Chennai",
    airline: "AirAsia",
    aircraft: "Airbus A320",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T13:30:00",
    destination: "Delhi",
    flightNumber: "I513",
    departureTime: "2024-03-15T10:00:00",
    seatsAvailable: 100,
  },
  {
    id: 13,
    gate: "A3",
    price: 5300,
    origin: "Chennai",
    airline: "IndiGo",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T15:00:00",
    destination: "Mumbai",
    flightNumber: "6E113",
    departureTime: "2024-03-15T12:00:00",
    seatsAvailable: 110,
  },
  {
    id: 14,
    gate: "B5",
    price: 5500,
    origin: "Chennai",
    airline: "Air India",
    aircraft: "Boeing 787",
    duration: "3 hours",
    arrivalTime: "2024-03-15T16:30:00",
    destination: "Bangalore",
    flightNumber: "AI216",
    departureTime: "2024-03-15T13:30:00",
    seatsAvailable: 90,
  },
  {
    id: 15,
    gate: "C4",
    price: 5900,
    origin: "Kolkata",
    airline: "SpiceJet",
    aircraft: "Boeing 737",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T14:30:00",
    destination: "Delhi",
    flightNumber: "SG319",
    departureTime: "2024-03-15T11:00:00",
    seatsAvailable: 100,
  },
  {
    id: 16,
    gate: "D6",
    price: 6100,
    origin: "Kolkata",
    airline: "Vistara",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T15:30:00",
    destination: "Mumbai",
    flightNumber: "UK424",
    departureTime: "2024-03-15T12:30:00",
    seatsAvailable: 120,
  },
  {
    id: 17,
    gate: "A7",
    price: 6800,
    origin: "Kolkata",
    airline: "GoAir",
    aircraft: "Airbus A320",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T17:30:00",
    destination: "Bangalore",
    flightNumber: "G827",
    departureTime: "2024-03-15T14:00:00",
    seatsAvailable: 80,
  },
  {
    id: 18,
    gate: "B8",
    price: 5200,
    origin: "Delhi",
    airline: "AirAsia",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T18:30:00",
    destination: "Chennai",
    flightNumber: "I529",
    departureTime: "2024-03-15T15:30:00",
    seatsAvailable: 90,
  },
  {
    id: 19,
    gate: "C9",
    price: 5400,
    origin: "Mumbai",
    airline: "IndiGo",
    aircraft: "Airbus A320",
    duration: "3 hours",
    arrivalTime: "2024-03-15T19:00:00",
    destination: "Chennai",
    flightNumber: "6E139",
    departureTime: "2024-03-15T16:00:00",
    seatsAvailable: 100,
  },
  {
    id: 20,
    gate: "D10",
    price: 6200,
    origin: "Bangalore",
    airline: "Air India",
    aircraft: "Boeing 787",
    duration: "3 hours 30 minutes",
    arrivalTime: "2024-03-15T20:30:00",
    destination: "Kolkata",
    flightNumber: "AI230",
    departureTime: "2024-03-15T17:00:00",
    seatsAvailable: 110,
  },
];

export const DUMMY_AIRPORT_CITIES = [
  {
    id: 1,
    city: "Mumbai",
    airportCode: "BOM",
    image: "https://source.unsplash.com/featured/?mumbai,heritage",
  },
  {
    id: 2,
    city: "Delhi",
    airportCode: "DEL",
    image: "https://source.unsplash.com/featured/?delhi,heritage",
  },
  {
    id: 3,
    city: "Bangalore",
    airportCode: "BLR",
    image: "https://source.unsplash.com/featured/?bangalore,heritage",
  },
  {
    id: 4,
    city: "Chennai",
    airportCode: "MAA",
    image: "https://source.unsplash.com/featured/?chennai,heritage",
  },
  {
    id: 5,
    city: "Kolkata",
    airportCode: "CCU",
    image: "https://source.unsplash.com/featured/?kolkata,heritage",
  },
  {
    id: 6,
    city: "Hyderabad",
    airportCode: "HYD",
    image: "https://source.unsplash.com/featured/?hyderabad,heritage",
  },
  {
    id: 7,
    city: "Pune",
    airportCode: "PNQ",
    image: "https://source.unsplash.com/featured/?pune,heritage",
  },
  {
    id: 8,
    city: "Ahmedabad",
    airportCode: "AMD",
    image: "https://source.unsplash.com/featured/?ahmedabad,heritage",
  },
  {
    id: 9,
    city: "Jaipur",
    airportCode: "JAI",
    image: "https://source.unsplash.com/featured/?jaipur,heritage",
  },
  {
    id: 10,
    city: "Lucknow",
    airportCode: "LKO",
    image: "https://source.unsplash.com/featured/?lucknow,heritage",
  },
  {
    id: 11,
    city: "Kochi",
    airportCode: "COK",
    image: "https://source.unsplash.com/featured/?kochi,heritage",
  },
  {
    id: 12,
    city: "Goa",
    airportCode: "GOI",
    image: "https://source.unsplash.com/featured/?goa,heritage",
  },
  {
    id: 13,
    city: "Bhopal",
    airportCode: "BHO",
    image: "https://source.unsplash.com/featured/?bhopal,heritage",
  },
  {
    id: 14,
    city: "Indore",
    airportCode: "IDR",
    image: "https://source.unsplash.com/featured/?indore,heritage",
  },
  {
    id: 15,
    city: "Vadodara",
    airportCode: "BDQ",
    image: "https://source.unsplash.com/featured/?vadodara,heritage",
  },
  {
    id: 16,
    city: "Surat",
    airportCode: "STV",
    image: "https://source.unsplash.com/featured/?surat,heritage",
  },
  {
    id: 17,
    city: "Nagpur",
    airportCode: "NAG",
    image: "https://source.unsplash.com/featured/?nagpur,heritage",
  },
  {
    id: 18,
    city: "Bhubaneswar",
    airportCode: "BBI",
    image: "https://source.unsplash.com/featured/?bhubaneswar,heritage",
  },
  {
    id: 19,
    city: "Coimbatore",
    airportCode: "CJB",
    image: "https://source.unsplash.com/featured/?coimbatore,heritage",
  },
  {
    id: 20,
    city: "Visakhapatnam",
    airportCode: "VTZ",
    image: "https://source.unsplash.com/featured/?visakhapatnam,heritage",
  },
  {
    id: 21,
    city: "Patna",
    airportCode: "PAT",
    image: "https://source.unsplash.com/featured/?patna,heritage",
  },
  {
    id: 22,
    city: "Kanpur",
    airportCode: "KNU",
    image: "https://source.unsplash.com/featured/?kanpur,heritage",
  },
  {
    id: 23,
    city: "Thiruvananthapuram",
    airportCode: "TRV",
    image: "https://source.unsplash.com/featured/?thiruvananthapuram,heritage",
  },
  {
    id: 24,
    city: "Kozhikode",
    airportCode: "CCJ",
    image: "https://source.unsplash.com/featured/?kozhikode,heritage",
  },
  {
    id: 25,
    city: "Mangalore",
    airportCode: "IXE",
    image: "https://source.unsplash.com/featured/?mangalore,heritage",
  },
  {
    id: 26,
    city: "Raipur",
    airportCode: "RPR",
    image: "https://source.unsplash.com/featured/?raipur,heritage",
  },
  {
    id: 27,
    city: "Ranchi",
    airportCode: "IXR",
    image: "https://source.unsplash.com/featured/?ranchi,heritage",
  },
  {
    id: 28,
    city: "Guwahati",
    airportCode: "GAU",
    image: "https://source.unsplash.com/featured/?guwahati,heritage",
  },
  {
    id: 29,
    city: "Jodhpur",
    airportCode: "JDH",
    image: "https://source.unsplash.com/featured/?jodhpur,heritage",
  },
  {
    id: 30,
    city: "Amritsar",
    airportCode: "ATQ",
    image: "https://source.unsplash.com/featured/?amritsar,heritage",
  },
];

export const DUMMY_TRAVEL_CATEGORIES = [
  {
    id: 1,
    name: "Flights",
    icon: "airplane-outline",
  },
  {
    id: 2,
    name: "Trains",
    icon: "train-outline",
  },
  {
    id: 3,
    name: "Cars",
    icon: "car-outline",
  },
  {
    id: 4,
    name: "Hotels",
    icon: "bed-outline",
  },
  {
    id: 5,
    name: "Bikes",
    icon: "bicycle-outline",
  },
  {
    id: 6,
    name: "Restaurants",
    icon: "restaurant-outline",
  },
];

export const DUMMY_TRAVEL_OFFERS = [
  {
    id: 1,
    title: "Early Bird Special",
    subTitle: "Book 30 days in advance and get a 20% discount.",
    image: "https://source.unsplash.com/100x100/?travel,earlybird",
  },
  {
    id: 2,
    title: "Last Minute Deal",
    subTitle: "Get up to 50% off on last minute hotel bookings.",
    image: "https://source.unsplash.com/100x100/?travel,lastminute",
  },
  {
    id: 3,
    title: "Weekend Getaway",
    subTitle: "Enjoy a 15% discount on weekend trips to select destinations.",
    image: "https://source.unsplash.com/100x100/?travel,weekend",
  },
];

export const DUMMY_INDIAN_AIRLINES = [
  {
    id: 1,
    name: "IndiGo",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/IndiGo_Logo.svg/1280px-IndiGo_Logo.svg.png",
  },
  {
    id: 2,
    name: "SpiceJet",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/SpiceJet_Logo.svg/1024px-SpiceJet_Logo.svg.png",
  },
  {
    id: 3,
    name: "Air India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Air_India_Logo.svg/1024px-Air_India_Logo.svg.png",
  },
  {
    id: 4,
    name: "GoAir",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/GoAir_Logo.svg/1024px-GoAir_Logo.svg.png",
  },
  {
    id: 5,
    name: "Vistara",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Vistara_Logo.svg/1280px-Vistara_Logo.svg.png",
  },
  {
    id: 6,
    name: "AirAsia",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/AirAsia_New_Logo_2017.svg/1024px-AirAsia_New_Logo_2017.svg.png",
  },
  {
    id: 7,
    name: "Go First",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Go_First_logo.svg/1024px-Go_First_logo.svg.png",
  },
  {
    id: 8,
    name: "TruJet",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Trujet_logo.svg/1024px-Trujet_logo.svg.png",
  },
  {
    id: 9,
    name: "Alliance Air",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Alliance_Air_Logo.svg/1024px-Alliance_Air_Logo.svg.png",
  },
];

export const cityNames = DUMMY_AIRPORT_CITIES.map((city) => city?.city) ?? [];
export const airlineNames =
  DUMMY_INDIAN_AIRLINES.map((city) => city?.name) ?? [];

export const DUMMY_FILTERS = [
  { id: 0, name: "sort", options: ["lowToHigh", "highToLow"] },
  { id: 1, name: "airline", options: airlineNames },
];
